### ISSUE TITLE
province data

### ISSUE THREAD

**Issue by Anna19031995** [alessiodl/COVID19Dashboard#3]
Hi! I was looking for the number of swabs that were made every day and along all this period in all italian provinces.. I would need them to complete an article, can you help me to find them?

thank you for the attention
Anna

**Comment by alessiodl** [comment]
Hi Anna, 
take a look at the official repository by Civil Protection Department. 

https://github.com/pcm-dpc/COVID-19

You can find daily swabs at regional level. Provinces are not available 

https://github.com/pcm-dpc/COVID-19/tree/master/dati-regioni

**Comment by Anna19031995** [comment]
Thank you very much!!
